/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import local.AccesoLocal;
import local.InicioServidor;
import local.PersistenciaImpl;
import remote.Sitio;
import remote.util.InterfaceManager;
import remote.util.InterfaceManager.Interfaces;

/**
 *
 * @author jdosornio
 */
public class VistaConexion extends javax.swing.JFrame {

    private final JTextField[] txtIPs = new JTextField[7];
    private final JTextField[] txtPuertos = new JTextField[7];
    private final JTextField[] txtInts = new JTextField[7];
    
    /**
     * Creates new form VistaConexion
     */
    public VistaConexion() {
        initComponents();
        txtIPs[6] = s7IP;
        txtPuertos[6] = s7Puerto;
        txtInts[6] = s7Int;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        s1IP = new javax.swing.JTextField();
        txtIPs[0] = s1IP;
        jLabel4 = new javax.swing.JLabel();
        s1Puerto = new javax.swing.JTextField();
        txtPuertos[0] = s1Puerto;
        jLabel23 = new javax.swing.JLabel();
        s1Int = new javax.swing.JTextField();
        txtInts[0] = s1Int;
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        s2IP = new javax.swing.JTextField();
        txtIPs[1] = s2IP;
        jLabel7 = new javax.swing.JLabel();
        s2Puerto = new javax.swing.JTextField();
        txtPuertos[1] = s2Puerto;
        jLabel24 = new javax.swing.JLabel();
        s2Int = new javax.swing.JTextField();
        txtInts[1] = s2Int;
        s3IP = new javax.swing.JTextField();
        txtIPs[2] = s3IP;
        jLabel8 = new javax.swing.JLabel();
        s3Puerto = new javax.swing.JTextField();
        txtPuertos[2] = s3Puerto;
        jLabel25 = new javax.swing.JLabel();
        s3Int = new javax.swing.JTextField();
        txtInts[2] = s3Int;
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        s4IP = new javax.swing.JTextField();
        txtIPs[3] = s4IP;
        jLabel14 = new javax.swing.JLabel();
        s4Puerto = new javax.swing.JTextField();
        txtPuertos[3] = s4Puerto;
        jLabel27 = new javax.swing.JLabel();
        s4Int = new javax.swing.JTextField();
        txtInts[3] = s4Int;
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        s5IP = new javax.swing.JTextField();
        txtIPs[4] = s5IP;
        jLabel17 = new javax.swing.JLabel();
        s5Puerto = new javax.swing.JTextField();
        txtPuertos[4] = s5Puerto;
        jLabel28 = new javax.swing.JLabel();
        s5Int = new javax.swing.JTextField();
        txtInts[4] = s5Int;
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        s6IP = new javax.swing.JTextField();
        txtIPs[5] = s6IP;
        jLabel20 = new javax.swing.JLabel();
        s6Puerto = new javax.swing.JTextField();
        txtPuertos[5] = s6Puerto;
        jLabel29 = new javax.swing.JLabel();
        s6Int = new javax.swing.JTextField();
        txtInts[5] = s6Int;
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        s7IP = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        s7Puerto = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        s7Int = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnConectarse = new javax.swing.JButton();
        btnIniciarServidor = new javax.swing.JButton();
        persistInt = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        persistPuerto = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel11.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel11.setText("Puerto:");

        jTextField8.setText("11973");

        jLabel26.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel26.setText("Interface:");

        jTextField18.setText("SItio3Capacisoft");

        jLabel12.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel12.setText("Sitio 3");

        jLabel13.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel13.setText("IP:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel1.setText("Sitio 1");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 1, 20)); // NOI18N
        jLabel2.setText("Conectarse a los sitios");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel3.setText("IP:");

        s1IP.setText("192.168.1.77");

        jLabel4.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel4.setText("Puerto:");

        s1Puerto.setText("11973");

        jLabel23.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel23.setText("Interface:");

        s1Int.setText("Sitio1Capacisoft");

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel5.setText("Sitio 2");

        jLabel6.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel6.setText("IP:");

        s2IP.setText("192.168.1.77");

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel7.setText("Puerto:");

        s2Puerto.setText("11974");

        jLabel24.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel24.setText("Interface:");

        s2Int.setText("Sitio2Capacisoft");

        s3IP.setText("192.168.1.77");

        jLabel8.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel8.setText("Puerto:");

        s3Puerto.setText("11975");

        jLabel25.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel25.setText("Interface:");

        s3Int.setText("Sitio3Capacisoft");

        jLabel9.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel9.setText("Sitio 3");

        jLabel10.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel10.setText("IP:");

        s4IP.setText("192.168.1.77");

        jLabel14.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel14.setText("Puerto:");

        s4Puerto.setText("11976");

        jLabel27.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel27.setText("Interface:");

        s4Int.setText("Sitio4Capacisoft");

        jLabel15.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel15.setText("Sitio 4");

        jLabel16.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel16.setText("IP:");

        s5IP.setText("192.168.1.77");

        jLabel17.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel17.setText("Puerto:");

        s5Puerto.setText("11977");

        jLabel28.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel28.setText("Interface:");

        s5Int.setText("Sitio5Capacisoft");

        jLabel18.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel18.setText("Sitio 5");

        jLabel19.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel19.setText("IP:");

        s6IP.setText("192.168.1.77");

        jLabel20.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel20.setText("Puerto:");

        s6Puerto.setText("11978");

        jLabel29.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel29.setText("Interface:");

        s6Int.setText("Sitio6Capacisoft");

        jLabel21.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel21.setText("Sitio 6");

        jLabel22.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel22.setText("IP:");

        s7IP.setText("192.168.1.77");

        jLabel30.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel30.setText("Puerto:");

        s7Puerto.setText("11979");

        jLabel31.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel31.setText("Interface:");

        s7Int.setText("Sitio7Capacisoft");

        jLabel32.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel32.setText("Sitio 7");

        jLabel33.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel33.setText("IP:");

        btnConectarse.setText("Conectarse");
        btnConectarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarse(evt);
            }
        });

        btnIniciarServidor.setText("Iniciar Servidor");
        btnIniciarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarServidor(evt);
            }
        });

        persistInt.setText("PersistInt");

        jLabel34.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel34.setText("Interface:");

        jLabel35.setFont(new java.awt.Font("Source Sans Pro", 1, 15)); // NOI18N
        jLabel35.setText("Puerto:");

        persistPuerto.setText("12006");

        jLabel36.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel36.setText("Persistencia");

        jButton1.setText("Mandar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarConexionesSitio(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addGap(2, 2, 2))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addGap(33, 33, 33))
                                                .addComponent(jLabel8)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(s3Int)
                                            .addComponent(s3Puerto)
                                            .addComponent(s3IP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel24)
                                            .addGap(2, 2, 2))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(33, 33, 33))
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(s2Int)
                                        .addComponent(s2Puerto)
                                        .addComponent(s2IP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(2, 2, 2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33))
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(s1Int)
                                .addComponent(s1Puerto)
                                .addComponent(s1IP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel29)
                                                .addGap(2, 2, 2))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel22)
                                                    .addGap(33, 33, 33))
                                                .addComponent(jLabel20)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(s6Int)
                                            .addComponent(s6Puerto)
                                            .addComponent(s6IP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel28)
                                            .addGap(2, 2, 2))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(33, 33, 33))
                                            .addComponent(jLabel17)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(s5Int)
                                        .addComponent(s5Puerto)
                                        .addComponent(s5IP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addGap(2, 2, 2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(33, 33, 33))
                                    .addComponent(jLabel14)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(s4Int)
                                .addComponent(s4Puerto)
                                .addComponent(s4IP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addGap(2, 2, 2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel33)
                                            .addGap(33, 33, 33))
                                        .addComponent(jLabel30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(s7Int)
                                    .addComponent(s7Puerto)
                                    .addComponent(s7IP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(persistInt)
                                    .addComponent(persistPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnIniciarServidor, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnConectarse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(s1IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s1Puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(s1Int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(s4IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s4Puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(s4Int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(s7IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s7Puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel30)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(s7Int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(s2IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s2Puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(s2Int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(persistPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(persistInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(s5IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s5Puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(s5Int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(s3IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s3Puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(s3Int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(s6IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s6Puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(s6Int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciarServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConectarse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarServidor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarServidor
        try {
            //Sitio
            String serverIp = s7IP.getText();
            int serverPuerto = Integer.parseInt(s7Puerto.getText());
            String serverInt = s7Int.getText();

            //Guardar datos de Sitio 7
            InterfaceManager.setConexionSitio(Interfaces.SITIO_7, serverIp,
                    serverPuerto, serverInt);

            //Persistencia
            int puerto = Integer.parseInt(persistPuerto.getText());
            String intfP = persistInt.getText();

            //Declarar la ip de esta computadora (linux)
            System.setProperty("java.rmi.server.hostname", serverIp);

            //Iniciar servicios
            InicioServidor.iniciarServidor(serverPuerto, serverInt, AccesoLocal.class);
            InicioServidor.iniciarServidor(puerto, intfP, PersistenciaImpl.class);

            //Guardar la interface de este mismo nodo
            InterfaceManager.addInterface("127.0.0.1", serverPuerto, serverInt);
            InterfaceManager.setInterfaceServicio(Interfaces.LOCALHOST, serverInt);

        } catch (RemoteException | NotBoundException ex) {
            Logger.getLogger(VistaConexion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_iniciarServidor

    private void conectarse(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarse

        //Validar si se tienen ya las conexiones guardadas
        if (!InterfaceManager.getInterfacesConexion().isEmpty() &&
                InterfaceManager.conexionRemota) {
            //Guardar los datos en los campos....
            Map<Interfaces, Object[]> datosConexion = InterfaceManager
                    .getInterfacesConexion();
            
            int noSitio = 0;
            
            //Guardar en los campos de texto
            for (Interfaces sitio : datosConexion.keySet()) {
                Object[] datos = datosConexion.get(sitio);
                
                switch(sitio) {
                    case SITIO_1:
                        s1IP.setText(datos[0].toString());
                        s1Puerto.setText(datos[1].toString());
                        s1Int.setText(datos[2].toString());
                        noSitio = 1;
                        break;
                        
                    case SITIO_2:
                        s2IP.setText(datos[0].toString());
                        s2Puerto.setText(datos[1].toString());
                        s2Int.setText(datos[2].toString());
                        noSitio = 2;
                        break;
                        
                    case SITIO_3:
                        s3IP.setText(datos[0].toString());
                        s3Puerto.setText(datos[1].toString());
                        s3Int.setText(datos[2].toString());
                        noSitio = 3;
                        break;
                        
                    case SITIO_4:
                        s4IP.setText(datos[0].toString());
                        s4Puerto.setText(datos[1].toString());
                        s4Int.setText(datos[2].toString());
                        noSitio = 4;
                        break;
                        
                    case SITIO_5:
                        s5IP.setText(datos[0].toString());
                        s5Puerto.setText(datos[1].toString());
                        s5Int.setText(datos[2].toString());
                        noSitio = 5;
                        break;
                        
                    case SITIO_6:
                        s6IP.setText(datos[0].toString());
                        s6Puerto.setText(datos[1].toString());
                        s6Int.setText(datos[2].toString());
                        noSitio = 6;
                        break;
                        
                    case SITIO_7:
                        s7IP.setText(datos[0].toString());
                        s7Puerto.setText(datos[1].toString());
                        s7Int.setText(datos[2].toString());
                        noSitio = 7;
                        break;
                }
                
                conectarSitio(datos[0].toString(), datos[1].toString(),
                        datos[2].toString(), noSitio);
            }
            
        } else {
            for (int i = 0; i < 6; i++) {
                String ip = txtIPs[i].getText();
                String puerto = txtPuertos[i].getText();
                String intf = txtInts[i].getText();

                if (!ip.isEmpty() && !puerto.isEmpty() && !intf.isEmpty()) {

                    Interfaces intfSitio = conectarSitio(ip, puerto, intf, i + 1);
                    
                    InterfaceManager.setConexionSitio(intfSitio, ip, puerto, intf);
                }
            }
        }
    }//GEN-LAST:event_conectarse

    private Interfaces conectarSitio(String ip, String puerto, String intf, int noSitio) {
        Interfaces intfSitio = null;
        try {
            InterfaceManager.addInterface(ip, Integer.parseInt(puerto), intf);
            
            //guardar el nombre de la interface
            String interfaceSitio = "SITIO_" + (noSitio);

            intfSitio = Interfaces.valueOf(interfaceSitio);
            
            InterfaceManager.setInterfaceServicio(intfSitio, intf);
            
        } catch (RemoteException | NotBoundException ex) {
            Logger.getLogger(VistaConexion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return intfSitio;
    }

    private void enviarConexionesSitio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarConexionesSitio
        // TODO add your handling code here:

        //Enviar a todas las interfaces
        for (Interfaces interfaceEnviar : InterfaceManager.getInterfacesRegistradas()) {
            try {
                //Saltarse el localhost
                if (interfaceEnviar.equals(Interfaces.LOCALHOST)) {
                    continue;
                }

                Map datosConexion = InterfaceManager.getInterfacesConexion();
                //Si es el destino remover esos datos
                if (datosConexion.containsKey(interfaceEnviar)) {
                    datosConexion.remove(interfaceEnviar);
                }

                //Enviar los datos de las conexiones
                Sitio sitio = InterfaceManager
                        .getInterface(InterfaceManager.getInterfaceServicio(interfaceEnviar));

                if (sitio != null) {
                    //Enviar los datos de la conexion
                    sitio.setConexionesSitos(datosConexion);
                }

            } catch (RemoteException | NotBoundException ex) {
                Logger.getLogger(VistaConexion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_enviarConexionesSitio

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectarse;
    private javax.swing.JButton btnIniciarServidor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField persistInt;
    private javax.swing.JTextField persistPuerto;
    private javax.swing.JTextField s1IP;
    private javax.swing.JTextField s1Int;
    private javax.swing.JTextField s1Puerto;
    private javax.swing.JTextField s2IP;
    private javax.swing.JTextField s2Int;
    private javax.swing.JTextField s2Puerto;
    private javax.swing.JTextField s3IP;
    private javax.swing.JTextField s3Int;
    private javax.swing.JTextField s3Puerto;
    private javax.swing.JTextField s4IP;
    private javax.swing.JTextField s4Int;
    private javax.swing.JTextField s4Puerto;
    private javax.swing.JTextField s5IP;
    private javax.swing.JTextField s5Int;
    private javax.swing.JTextField s5Puerto;
    private javax.swing.JTextField s6IP;
    private javax.swing.JTextField s6Int;
    private javax.swing.JTextField s6Puerto;
    private javax.swing.JTextField s7IP;
    private javax.swing.JTextField s7Int;
    private javax.swing.JTextField s7Puerto;
    // End of variables declaration//GEN-END:variables
}
